### ISSUE TITLE
Tabby : 'StateObject' is only available in iOS 14.0 or newer

### ISSUE THREAD

**Issue by sreenathtv18** [tabby-ai/tabby-ios-sdk#14]
Compiler error: Tabby SDK is not working
'StateObject' is only available in iOS 14.0 or newer

<img width="937" alt="Screenshot 2023-06-14 at 2 51 00 PM" src="https://github.com/tabby-ai/tabby-ios-sdk/assets/11013985/e9fc2d9a-1035-4430-9826-5f352dc02a10">

**Comment by gregoryvit** [comment]
Resolved in https://github.com/tabby-ai/tabby-ios-sdk/pull/15
