### ISSUE TITLE
Unable to decode error in configure(forPayment .... response

### ISSUE THREAD

**Issue by cecipirotto** [tabby-ai/tabby-ios-sdk#27]
When I'm calling `TabbySDK.shared.configure(forPayment: ....)` using the TabbyPayment [specified in the example](https://github.com/tabby-ai/tabby-ios-sdk?tab=readme-ov-file#2-prepare-view) I encounter an "unable to decode" error.

While debugging into the SDK code, I discovered that the error occurs in the NetworkService class at line 55, where it attempts to decode the server response, but the response appears to be in HTML format.

I look forward to a prompt response to resolve this issue.

**Comment by ibtikarat** [comment]
is there any update?

**Comment by HusseinFlaifl** [comment]
is there any update?

**Comment by AlexSib85** [comment]
Try to use prod environment with test keys, it's help to me
